package ru.stqa.pft.addressbook.tests;
// Generated by Selenium IDE

import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.util.concurrent.TimeUnit;

public class TestgroupTest {
  FirefoxDriver wd;

  @BeforeMethod
  public void setUp() throws Exception{
    System.setProperty("webdriver.gecko.driver","c:/temp/geckodriver.exe");
    wd = new FirefoxDriver();
    wd.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
  }

  @After
  public void tearDown() {
    wd.quit();
  }

  @Test
  public void testgroup() {
    wd.get("http://localhost/addressbook/");
    wd.manage().window().setSize(new Dimension(1282, 693));
    wd.findElement(By.xpath("//input[@name='user']")).sendKeys("admin");
    wd.findElement(By.xpath("//input[@name='pass']")).sendKeys("secret");
    wd.findElement(By.xpath("//input[@value='Login']")).click();
    wd.findElement(By.xpath("//a[contains(text(),'groups')]")).click();
    wd.findElement(By.xpath("//input[@name='new']")).click();
    wd.findElement(By.xpath("//input[@name='group_name']")).click();
    wd.findElement(By.xpath("//input[@name='group_name']")).sendKeys("test3");
    wd.findElement(By.xpath("//textarea[@name='group_header']")).sendKeys("test3_2\\n");
    wd.findElement(By.xpath("//textarea[@name='group_footer']")).click();
    wd.findElement(By.xpath("//input[@name='submit']")).click();
    wd.findElement(By.xpath("//a[contains(text(),'group page')]")).click();
  }
}
